RUIeServer/estadistica/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.estadistica, name="estadistica"),
     path('buscar/', views.busqueda, name="busqueda"),
     path('reincidencia/', views.reincidencia, name="reincidente"),

#    Consultas en ajax
     path('buscar_rescate/', views.buscar_reincidente_ajax, name='buscar_rescate'),
     path('reincidentes_dia/', views.reincidentes_xdia_ajax, name='reincidencia'),
     path('reincidentes_fechas/', views.reincidentes_xfechas_ajax, name='reincidenciaFechas'),

     path("pdf/", views.generar_pdf, name="generar_pdf"),
     path("pdfT/", views.generar_pdfT, name="generar_pdfT"),
     path("pdf_ceco/", views.generar_pdf_ceco, name="generar_pdf_ceco"),
     path("cuadro_datos/", views.generar_cuadro_diario, name="generar_cuadro_diario"),
     path("excelT/", views.exportar_excel_reporteT, name="exportar_excel_reporteT"),
]

RUIeServer/serverRUI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from usuario import views
from usuarioL.views import index, pagina404
from dashboard import views as viewsDash
from django.contrib.auth import views as viewsL
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', index, name="index"),

    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('log-in/', viewsL.LoginView.as_view(template_name= 'base/log_in.html'), name='log-in'),
    path('log-out', viewsL.LogoutView.as_view(), name="logout" ),

    path('login/validar/', views.login_user),
    path('info/', include('usuario.urls')),

    path('registro/insertR', views.insert_rescates),
    path('registro/insertC', views.insert_conteo),
    path('registro/insertD', views.insert_disuadidos),
    path('descargas/', views.servirApps, name="descargas"),
    path('descargas/apk', views.downloadAPK, name="descarga_android"),

    path('estadistica/', include('estadistica.urls')),
    # path('info/pruebas/edoFuerza/editarEdoFuerza/<int:id_edo_fuerza>', viewsDash.editar_estado_fuerza, name='editar_estado_fuerza'),
    # path('info/pruebas/usuarios/eliminarUsuario/<int:id_usuario>', viewsDash.eliminarUsuario, name='eliminar_usuario'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pagina404

RUIeServer/usuario/urls.py
from django.urls import path, include
from usuario import views

urlpatterns = [
    path('cargarPais', views.cargarPais, name="cargar_pais"),
    path('cargarFuerza', views.cargarEdoFuerza, name="cargar_fuerza"),
    #path('dashboard/', views.cargarEdoF, name="cargar_f"),
    path('cargarMunicipios', views.cargarMunicipios, name="cargar_municipios"),
    path('cargarPuntosI', views.cargarPuntoI, name="cargar_puntoI"),
    path('cargarInadmitidos', views.cargarInadmitidos, name="cargar_Inadmitidos"),

    path('Usuarios', views.cargaMasivaUser, name="cargar_usuarios"),
    path('Paises', views.infoPaises),
    path('Fuerza', views.infoEstadoFuerza),
    path('Municipios', views.infoMunicipios),
    path('PuntosI', views.infoPuntosInterna),
    path('frases', views.infoFrases),
    
    path('fechas', views.generarExcelFechas, name="fechas_descarga"),
    path('fechasOR', views.generarExcelFechasOR, name="fechas_OR"),

    path('descargaN', views.generarExcelNombres),
    path('descargaC', views.generarExcelConteo),
    path('descargaD', views.pagDuplicados),

    path('descargaD_a', views.downloadDuplicados, name="descarga_duplicados"),
    path('descargaTab22', views.generarExcelTab),
    path('descargaExcel', views.generarExcelORs, name="descarga_excel"),
    path('descargaExcelUsuarios', views.generarExcelUsuarios, name="descarga_excelUsuarios"),
    path('descargaExcelEdoFuerza', views.generarExcelEdoFuerza, name="descarga_excelEdoFuerza"),
    path('descargaExcelPuntosI', views.generarExcelPuntosI, name="descarga_excelPuntosI"),

    path('updateApp', views.msgUpdateUrl, name="info_app"),

    path('politica_privacidad', views.politica_privacidad, name="info_politica_privacidad"),

]

RUIeServer/estadistica/models.py
from django.db import models

# Create your models here.

RUIeServer/usuario/models.py
from django.db import models
from django.contrib.auth.hashers import make_password

# Create your models here.

class Usuario(models.Model):
    types_ORS = [
        ("1", "AGUASCALIENTES"),
        ("2", "BAJA CALIFORNIA"),
        ("3", "BAJA CALIFORNIA SUR"),
        ("4", "CAMPECHE"),
        ("5", "COAHUILA"),
        ("6", "COLIMA"),
        ("7", "CHIAPAS"),
        ("8", "CHIHUAHUA"),
        ("9", "CDMX"),
        ("10", "DURANGO"),
        ("11", "GUANAJUATO"),
        ("12", "GUERRERO"),
        ("13", "HIDALGO"),
        ("14", "JALISCO"),
        ("15", "EDOMEX"),
        ("16", "MICHOACÁN"),
        ("17", "MORELOS"),
        ("18", "NAYARIT"),
        ("19", "NUEVO LEÓN"),
        ("20", "OAXACA"),
        ("21", "PUEBLA"),
        ("22", "QUERÉTARO"),
        ("23", "QUINTANA ROO"),
        ("24", "SAN LUIS POTOSÍ"),
        ("25", "SINALOA"),
        ("26", "SONORA"),
        ("27", "TABASCO"),
        ("28", "TAMAULIPAS"),
        ("29", "TLAXCALA"),
        ("30", "VERACRUZ"),
        ("31", "YUCATÁN"),
        ("32", "ZACATECAS"),
    ]
    types_user = [
        ("1" , "Administrador"),
        ("2", "Validador"),
        ("3", "Capturador"),
    ]
    types_disp = [
        ("1" , "Android"),
        ("2", "IPhone"),
        ("3", "Otro"),
    ]
    idUser = models.AutoField(primary_key=True)
    nickname = models.CharField(max_length = 30)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=200)
    password = models.CharField(max_length=250)
    str_pass = models.CharField(max_length=250, blank=True, default="")
    estado = models.CharField(max_length=2, choices=types_ORS, default="9")
    tipo = models.CharField(max_length=1, choices=types_user, default="3")
    tipo_disp = models.CharField(max_length=1, choices=types_disp, default="1")

    def save(self, *args, **kwargs):
        self.password = make_password(self.password)
        super(Usuario, self).save(*args, **kwargs)

    def __str__(self):
        return  " {id}, {nickname}, {state}, {type}".format(id = self.idUser, nickname = self.nickname, state = self.estado, type = self.tipo)

class Paises(models.Model):
    idPais = models.AutoField(primary_key=True)
    nombre_pais = models.CharField(max_length=250)
    iso3 = models.CharField(max_length=3, null=True)

    def __str__(self):
        return " {id}, {pais}, {iso3}".format(id = self.idPais, pais = self.nombre_pais, iso3 = self.iso3)
    
class Frases(models.Model):
    quote = models.CharField(max_length=250)
    author = models.CharField(max_length=250)

    def __str__(self):
        return " {quote}, {author}".format(
            quote = self.quote[0:30], 
            author = self.author)
    
class MsgUpdate(models.Model):
    idMsg = models.AutoField(primary_key=True)
    version = models.CharField(max_length=25)
    info = models.BooleanField(default=False)
    msg = models.CharField(max_length=500,blank=True)

    def __str__(self):
        return "{id} -> {version}v, {msg}".format(
            id = self.idMsg,
            version = self.version,
            msg = self.msg[0:25]) 
    
class Municipios(models.Model):
    idMunicipio = models.AutoField(primary_key=True)
    estado = models.CharField(max_length=250)
    estadoAbr = models.CharField(max_length=50)
    nomMunicipio = models.CharField(max_length=250)

    def __str__(self):
        return " {estadoAbr}, {nomMunicipio}".format(
            estadoAbr = self.estadoAbr, 
            nomMunicipio = self.nomMunicipio)


class PuntosInternacion(models.Model):
    idPuntoInter = models.AutoField(primary_key=True)
    nombrePunto = models.CharField(max_length=100)
    estadoPunto = models.CharField(max_length=100)
    tipoPunto = models.CharField(max_length=50)

    def __str__(self):
        return " {nombrePunto}, {estadoPunto}, {tipoPunto}".format(
            nombrePunto = self.nombrePunto, 
            estadoPunto = self.estadoPunto, 
            tipoPunto = self.tipoPunto)

class Inadmitido(models.Model):
    GENERO_CHOICES = [
        ('H', 'Hombre'),
        ('M', 'Mujer'),
        ('X', 'No especificado'),
    ]

    fecha_hora = models.DateTimeField(db_index=True)
    oficina = models.CharField(max_length=50, db_index=True)
    puntoInter = models.CharField(max_length=100)
    nac = models.CharField(max_length=100, db_index=True)
    nombreCompleto = models.CharField(max_length=250)
    nacimiento = models.DateField()
    genero = models.CharField(
        max_length=1,
        choices=GENERO_CHOICES,
        db_index=True,
        default="X"
    )
    edad = models.IntegerField( null=True, verbose_name="Edad")

    def __str__(self):
        return "{fecha}: {oficina} -->[{nac}={adulto},{genero}]".format(
            fecha = self.fecha_hora.strftime("%d/%m/%Y"),
            oficina = self.oficina,
            nac = self.nac, 
            adulto = "A" if self.edad >= 18 else "M",
            genero=self.genero)

class EstadoFuerza(models.Model):
    idEdoFuerza = models.AutoField(primary_key=True)
    oficinaR = models.CharField(max_length=50)
    numPunto = models.IntegerField()
    nomPuntoRevision = models.CharField(max_length=350)
    tipoP = models.CharField(max_length=50)
    ubicacion = models.CharField(max_length=300)
    coordenadasTexto = models.CharField(max_length=300)
    latitud = models.FloatField(default=0.0)
    longitud = models.FloatField(default=0.0)
    personalINM = models.IntegerField()
    personalSEDENA = models.IntegerField()
    personalMarina = models.IntegerField()
    personalGuardiaN = models.IntegerField()
    personalOTROS = models.IntegerField()
    vehiculos = models.IntegerField()
    seccion = models.IntegerField()

    def __str__(self):
        return "{id}, {oficina}, {nomPuntoRevision} --> {tipoP}".format(id = self.idEdoFuerza, 
                                                                      oficina = self.oficinaR, 
                                                                      nomPuntoRevision = self.nomPuntoRevision[0:25], 
                                                                      tipoP = self.tipoP)


class RescatePunto(models.Model):
    idRescate = models.AutoField(primary_key=True)
    oficinaRepre = models.CharField(max_length=50, db_index=True)
    fecha = models.CharField(max_length=10, db_index=True)
    hora = models.CharField(max_length=5)
    
    nombreAgente = models.CharField(max_length=300,blank=True)

    aeropuerto = models.BooleanField(default=False)
    carretero = models.BooleanField(default=False)
    tipoVehic = models.CharField(max_length=30, blank=True)
    lineaAutobus = models.CharField(max_length=50, blank=True)
    numeroEcono = models.CharField(max_length=50, blank=True)
    placas = models.CharField(max_length=20, blank=True)

    vehiculoAseg = models.BooleanField(default=False)
    casaSeguridad = models.BooleanField(default=False)
    centralAutobus = models.BooleanField(default=False)
    ferrocarril = models.BooleanField(default=False)
    empresa = models.CharField(max_length=150, blank=True)
    hotel = models.BooleanField(default=False)
    nombreHotel = models.CharField(max_length=100, blank=True)
    
    puestosADispo = models.BooleanField(default=False)
    juezCalif = models.BooleanField(default=False)
    reclusorio = models.BooleanField(default=False)
    policiaFede = models.BooleanField(default=False)
    dif = models.BooleanField(default=False)
    policiaEsta = models.BooleanField(default=False)
    policiaMuni = models.BooleanField(default=False)
    guardiaNaci = models.BooleanField(default=False)
    fiscalia = models.BooleanField(default=False)
    otrasAuto = models.BooleanField(default=False)

    voluntarios = models.BooleanField(default=False)
    otro = models.BooleanField(default=False)
    presuntosDelincuentes = models.BooleanField(default=False)
    numPresuntosDelincuentes = models.IntegerField()
    municipio = models.CharField(max_length=200, blank=True)
    puntoEstra = models.CharField(max_length=250, blank=True, db_index=True)
    
    nacionalidad = models.CharField(max_length=100)
    iso3 = models.CharField(max_length=3)
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=150)
    noIdentidad = models.CharField(max_length=50)
    parentesco = models.CharField(max_length=50, blank=True)
    fechaNacimiento = models.CharField(max_length=10)
    sexo = models.BooleanField(default=False)
    embarazo = models.BooleanField(default=False)
    numFamilia = models.IntegerField(blank=True)
    edad = models.IntegerField()

    def __str__(self):
        tipoE = ""
        tipo= ""
        if(self.edad > 18):
            tipoE = "A"
        else:
            tipoE = "NNA"

        if(self.aeropuerto):
            tipo = "Aeropuerto"
        elif(self.carretero):
            tipo= "Carretero"
        elif(self.casaSeguridad):
            tipo= "Casa de Seguridad"
        elif(self.centralAutobus):
            tipo= "Central de Autobús"
        elif(self.ferrocarril):
            tipo= "Ferrocarril"
        elif(self.hotel):
            tipo= "Hotel"
        elif(self.puestosADispo):
            tipo= "Puestos a Disposición"
        elif(self.voluntarios):
            tipo= "Voluntarios"
        elif(self.otro):
            tipo= "Otro"
        else:
            tipo = ""
        return "{id}.- OR: {oficinaRepre}, Fecha: {fecha} {hora}, Tipo: {tipo} --> {iso3}, {tipoE}".format(id = self.idRescate, 
                                                                      oficinaRepre = self.oficinaRepre, 
                                                                      fecha = self.fecha, 
                                                                      hora = self.hora, 
                                                                      tipo = tipo, 
                                                                      iso3 = self.iso3, 

RUIeServer/estadistica/forms.py
from django import forms

from usuario.models import Paises

# class ArchivoForm(forms.ModelForm):
#     class Meta:
#         model = RescatePunto
#         fields = ['nombre', 'apellidos', ]

RUIeServer/estadistica/templates/estadistica/cuadroDATOS.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Cuadro Datos {{ fecha }}</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <style>
        @page {
            /* size: A4 landscape; Establecer formato horizontal */
            size: A4 portrait; /* Establecer formato vertical */
            margin: 10mm;
        }

        body {
            font-family: 'Montserrat', sans-serif;
            padding: 0;
        }
        h5 {
            text-align: center;
            align-items: center;
            margin-top: -10px;
            margin-bottom: -10px;
        }
        h6 {
            text-align: center;
            align-items: center;
            margin-bottom: -4px;
        }
        
        .fecha {
            text-align: right;
            font-size: 14px;
            margin-bottom: 10px;
        }

        .letraT3 { 
            color:rgb(244, 244, 244);
            background-color:rgb(40, 92, 77);  /* Color de fondo */
            writing-mode: vertical-lr; /* Texto en vertical (de abajo hacia arriba) */
            font-size: 3pt;
            border: 1px solid rgb(255, 255, 255); 
            text-align: center;
        }

        .page-break {
            page-break-before: always;
        }

        .tabla-oficina {
            width: 80%;
            border-collapse: collapse;
            margin: auto;
        }

        .tabla-oficina th, .tabla-oficina td {
            border: 1px solid black;
            padding: 5px;
            text-align: center;
            font-size: 10pt;
        }

        .tabla-oficina th {
            background-color:rgb(255, 255, 255); 
            color: rgb(0, 0, 0);
            font-weight: bold;
        }

        .tabla-oficina td {
            color: rgb(139,107,65);
        }

        .tabla-oficina tr:last-child td {
            background-color: rgb(139,107,65);
            color: rgb(250, 250, 250); 
            font-weight: bold; /* Opcional: negrita */
        }


        .tabla-oficina1 {
            width: 80%;
            border-collapse: collapse;
            margin: auto;
        }

        .tabla-oficina1 th, .tabla-oficina1 td {
            border: 1px solid black;
            padding: 5px;
            text-align: center;
            font-size: 10pt;
        }

        .tabla-oficina1 th {
            background-color:rgb(255, 255, 255); 
            color: rgb(0, 0, 0);
            font-weight: bold;
        }

        .tabla-oficina1 td {
            color: rgb(112,48,160);
        }

        .tabla-oficina1 tr:last-child td {
            background-color: rgb(112,48,160);
            color: rgb(250, 250, 250); 
            font-weight: bold; /* Opcional: negrita */
        }

        .tabla-resumen {
            width: 45%; /* 🔹 3 columnas sin perder espacio */
            border-collapse: collapse;
            margin-bottom: 10px;
            margin: auto;
        }

        .tabla-resumen th, .tabla-resumen td {
            border: 1px solid black;
            padding: 5px;
            text-align: center;
            font-size: 10pt;
        }

        .tabla-resumen th {
            background-color:rgb(255, 255, 255); 
            color:  rgb(98,17,50);
            font-weight: bold;
        }

        .tabla-resumen td {
            color: rgb(0, 0, 0);
        }

        .tabla-resumen tr:last-child td {
            background-color: rgb(98,17,50);
            color: rgb(250, 250, 250); 
            font-weight: bold; /* Opcional: negrita */
        }

        .letras-DIF {
            color: rgb(112,48,160);
            text-align: center;
        }

        .letras-EM {
            color: rgb(40, 92, 77); 
            text-align: center;
        }

        .letras-Tit {
            color: rgb(5, 11, 9); 
            text-align: center;
        }

        .contenedor-2T {
            margin-top: 40px;
            display: grid;
            grid-template-columns: 1fr 1fr;
        }

        .contenedor-datos {
            margin: 0;
            display: grid;
            grid-template-rows: auto 1fr auto; /* Encabezado, contenido, pie de página */
            height: 100vh;
        }

        .color-temp td {
            background-color: rgb(217, 217, 217);
        }

        .letras-temp td:last-child {
            color: rgb(157,36,73
            );
        }

        .texto-f {
            font-size: 8pt;
            text-indent: 30px;
            text-align: justify;
            line-height: 1.5;
        }

        .sangria {
            text-indent: 20px; /* Sangría en la primera línea */
        }
        
        .justificado {
            text-align: justify;
        }

        .espaciado {
            line-height: 1.5; /* Aumenta el espacio entre líneas */
        }

    </style>
</head>
<body>
    <div class="contenedor-datos">
        
        <div>
            <h4 class="letras-Tit">INSTITUTO NACIONAL DE MIGRACIÓN<br>DIRECCIÓN GENERAL DE OFICINAS DE REPRESENTACION</h4>

            <div>
                <h3 class="letras-Tit">Cuadro Datos<br>{{ fecha }}</h3>
            </div>

            <table class='tabla-resumen'>
                <thead>
                    <tr>
                        <th>FECHA</th>
                        <th>{{ fecha }}</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Rescatados:</td>
                        <td>{{ rescatados }}</td>
                    </tr>
                    <tr class="letras-temp">
                        <td>Reincidentes:</td>
                        <td>-{{ reincidentes }}</td>
                    </tr>
                    <tr class="color-temp">
                        <td>Subtotal:</td>
                        <td>{{ subtotal1 }}</td>
                    </tr>
                    <tr class="letras-temp">
                        <td>Inadmitidos:</td>
                        <td>-{{ inadmitidos }}</td>
                    </tr>
                    <tr class="color-temp">
                        <td>Subtotal:</td>
                        <td>{{ subtotal2 }}</td>
                    </tr>
                    <tr class="letras-temp">
                        <td>Retornados:</td>
                        <td>-{{ retornados }}</td>
                    </tr>
                    <tr class="color-temp">
                        <td>Subtotal:</td>
                        <td><strong>{{ rescates_nuevos }}</strong></td>
                    </tr>
                    <tr>
                        <td>De estos:</td>
                        <td>{{ EM_total }} Alojados en EM y<BR>{{ DIF_total }} canalizados al DIF</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="contenedor-2T">
            <div>
                <h3 class="letras-EM">Alojados en EM</h3>
                <table class='tabla-oficina'>
                    <thead>
                        <tr>
                            <th>NACIONALIDAD</th>
                            <th>TOTAL</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for oficina, datos in rescates_EM.items %}
                        <tr>
                            <td>{{ oficina }}</td>
                            <td>{{ datos.total_EM }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="2"> <strong>Sin rescates.</strong></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div>
                <h3 class="letras-DIF">Alojados en DIF/ALBERGUE</h3>
                <table class='tabla-oficina1'>
                    <thead>
                        <tr>
                            <th>NACIONALIDAD</th>
                            <th>TOTAL</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for oficina, datos in rescates_DIF.items %}
                        <tr>
                            <td>{{ oficina }}</td>
                            <td>{{ datos.total_DIF }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="2"> <strong>Sin rescates.</strong></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <br>
        <br>

        <p class="texto-f">
            Por lo que hace al número de rescates reportados, se precisa, que:<br><br>
            1.El mayor porcentaje de rescates, son extranjeros que se quedaron en Territorio Nacional, esperando cita de CBP-ONE y ahora son detectados en trayecto hacia el sur, solicitando el retorno voluntario su país de origen.<br><br>
            2.En el caso de Guatemala y Honduras se continúa con retornos inmediatos y los programados vía aérea y terrestre al interior de sus países.<br><br>
            3.En el caso de los venezolanos (que representan el mayor porcentaje de extranjeros en situación irregular en nuestro país) cada día se incrementa el número de solicitantes, para el Retorno Voluntario a su país.
        </p>

    </div>

</body>
</html>

RUIeServer/estadistica/templates/estadistica/reincidentes.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}Estadistica{% endblock title %}

{% block estadistica %}
    {% if request.user.is_superuser %}
        <a href="{% url 'estadistica' %}" class="bg-inm-verde-100 text-white px-6 py-3 rounded-xl hover:bg-inm-marron-200">Estadistica</a>
    {% endif %}
{% endblock estadistica %}

{% block styles %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% endblock styles %}

{% block content %}

<div class="flex-grow flex flex-col justify-center items-center p-4">
    
    <!-- Fila Superior -->
    <div class="bg-white p-4 rounded-lg shadow mb-8">
        <h2 class="text-xl font-semibold text-center">Ingresa los datos</h2>
        <form id="form-buscar">
            {% csrf_token %}
            <label for="id_nombre">Nombre:</label>
            <input type="text" name="nombre" id="id_nombre">
            
            <label for="id_apellidos">Apellido:</label>
            <input type="text" name="apellidos" id="id_apellidos">

            <label for="id_nacioalidad">Nacionalidad:</label>
            <input type="text" name="Nacionalidad" id="id_nacionalidad">
            
            <button type="submit">Buscar</button>
        </form>
    </div>

    <div id="loading" hidden class="bg-white p-4 rounded-lg shadow mb-8">Cargando resultados...</div>

    <!-- Contenedor de tabla -->
    <div class="bg-white p-4 rounded-lg shadow mb-8 w-full max-w-4xl">
      <table id="tabla_incidencias" class="min-w-full divide-y divide-gray-200">
        <thead>
          <tr>
            <th class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">No.</th>
            <th class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Fecha</th>
            <th class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">OR</th>
            <th class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Punto Estrategico</th>
            <th class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nombre</th>
            <th class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">apellidos</th>
            <th class="px-6 py-3 bg-gray-100 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nacionalidad</th>
          </tr>
        </thead>
        <tbody id="resultados" class="bg-white divide-y divide-gray-200"> </tbody>
      </table>
    </div>

</div>

<script>
    $(document).ready(function() {
        $('#form-buscar').on('submit', function(e) {
            e.preventDefault();

            $('#loading').show();

            let nombre = $('#id_nombre').val();
            let apellidos = $('#id_apellidos').val();
            let nacionalidad = $('#id_nacionalidad').val();

            $.ajax({
                url: '{% url "buscar_rescate" %}',
                type: 'GET',
                data: {
                    'nombre': nombre,
                    'apellidos': apellidos,
                    'nacionalidad': nacionalidad,
                },
                success: function(response) {
                    $('#loading').hide();

                    let resultados = $('#resultados');
                    resultados.empty(); // Limpiar resultados previos

                    if (response.data.length > 0) {
                        response.data.forEach(function(rescate) {
                            resultados.append(
                                `<tr>
                                    <td class="text-center">${rescate.No}</td>
                                    <td class="text-center">${rescate.fecha}</td>
                                    <td class="text-center">${rescate.oficina}</td>
                                    <td class="text-center">${rescate.punto}</td>
                                    <td class="text-center">${rescate.nombre}</td>
                                    <td class="text-center">${rescate.apellidos}</td>
                                    <td class="text-center">${rescate.nacionalidad}</td>
                                </tr>`
                            );
                        });
                    } else {
                        resultados.append('<tr><td colspan="6">No se encontraron resultados</td></tr>');
                    }
                },
                error: function() {
                    $('#loading').hide();
                    alert('Error al buscar los rescates');
                }
            });
        });
    });
</script>

{% endblock content %}