RUIeServer/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.dashboard, name="dashboard"),
     path('datos/', views.mostrarData, name="mostrar"),
     path('editar/<int:pk>', views.editarData, name="editar"),
     path('datos/fecha', views.datos_fecha, name="datos_por_fecha"),
     path('datos/fechas', views.datos_fechas, name="datos_por_fechas"),
     path('datos/eliminarM', views.eliminar_registros, name="eliminar_varios_registros"),
     path('datos/<int:year>/<int:month>/<int:day>/', views.tabla_registros, name='tabla_registros_fecha'),


     path('edoFuerza', views.edoFuerza, name="pagina_pruebas_edoFuerza"),
     path('edoFuerza/editarEdoFuerza/<int:id_edo_fuerza>', views.editar_estado_fuerza, name='editar_estado_fuerza'),
     path('edoFuerza/eliminarEdoFuerza/<int:id_edo_fuerza>', views.eliminarEdoFuerza, name='eliminar_estado_fuerza'),
     path('edoFuerza/anadirPunto', views.agregar_punto, name='agregar_punto'),

     path('puntosI', views.puntosI, name="paginaPuntosI"),
     path('puntosI/anadirPuntoInternacion', views.agregar_puntoInternacion, name='agregar_puntoInternacion'),
     path('puntosI/editarPuntoI/<int:id_puntoI>', views.editar_puntoInternacion, name='editar_puntoI'),
     path('puntosI/eliminarPuntoI/<int:id_puntoI>', views.eliminarPuntoI, name='eliminar_PuntoI'),

     path('usuarios', views.Usuarios, name="pagina_pruebas_usuarios"),
     path('usuarios/editarUsuario/<int:id_usuario>', views.editar_usuario, name='editar_usuario'),
     path('usuarios/anadirUsuario', views.agregar_usuario, name='agregar_usuario'),
     path('usuarios/eliminarUsuario/<int:id_usuario>', views.eliminarUsuario, name='eliminar_usuario'),
]

RUIeServer/serverRUI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from usuario import views
from usuarioL.views import index, pagina404
from dashboard import views as viewsDash
from django.contrib.auth import views as viewsL
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', index, name="index"),

    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('log-in/', viewsL.LoginView.as_view(template_name= 'base/log_in.html'), name='log-in'),
    path('log-out', viewsL.LogoutView.as_view(), name="logout" ),

    path('login/validar/', views.login_user),
    path('info/', include('usuario.urls')),

    path('registro/insertR', views.insert_rescates),
    path('registro/insertC', views.insert_conteo),
    path('registro/insertD', views.insert_disuadidos),
    path('descargas/', views.servirApps, name="descargas"),
    path('descargas/apk', views.downloadAPK, name="descarga_android"),

    path('estadistica/', include('estadistica.urls')),
    # path('info/pruebas/edoFuerza/editarEdoFuerza/<int:id_edo_fuerza>', viewsDash.editar_estado_fuerza, name='editar_estado_fuerza'),
    # path('info/pruebas/usuarios/eliminarUsuario/<int:id_usuario>', viewsDash.eliminarUsuario, name='eliminar_usuario'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pagina404

RUIeServer/usuario/urls.py
from django.urls import path, include
from usuario import views

urlpatterns = [
    path('cargarPais', views.cargarPais, name="cargar_pais"),
    path('cargarFuerza', views.cargarEdoFuerza, name="cargar_fuerza"),
    #path('dashboard/', views.cargarEdoF, name="cargar_f"),
    path('cargarMunicipios', views.cargarMunicipios, name="cargar_municipios"),
    path('cargarPuntosI', views.cargarPuntoI, name="cargar_puntoI"),
    path('cargarInadmitidos', views.cargarInadmitidos, name="cargar_Inadmitidos"),

    path('Usuarios', views.cargaMasivaUser, name="cargar_usuarios"),
    path('Paises', views.infoPaises),
    path('Fuerza', views.infoEstadoFuerza),
    path('Municipios', views.infoMunicipios),
    path('PuntosI', views.infoPuntosInterna),
    path('frases', views.infoFrases),
    
    path('fechas', views.generarExcelFechas, name="fechas_descarga"),
    path('fechasOR', views.generarExcelFechasOR, name="fechas_OR"),

    path('descargaN', views.generarExcelNombres),
    path('descargaC', views.generarExcelConteo),
    path('descargaD', views.pagDuplicados),

    path('descargaD_a', views.downloadDuplicados, name="descarga_duplicados"),
    path('descargaTab22', views.generarExcelTab),
    path('descargaExcel', views.generarExcelORs, name="descarga_excel"),
    path('descargaExcelUsuarios', views.generarExcelUsuarios, name="descarga_excelUsuarios"),
    path('descargaExcelEdoFuerza', views.generarExcelEdoFuerza, name="descarga_excelEdoFuerza"),
    path('descargaExcelPuntosI', views.generarExcelPuntosI, name="descarga_excelPuntosI"),

    path('updateApp', views.msgUpdateUrl, name="info_app"),

    path('politica_privacidad', views.politica_privacidad, name="info_politica_privacidad"),

]

RUIeServer/dashboard/models.py
from django.db import models

# Create your models here.

RUIeServer/usuario/models.py
from django.db import models
from django.contrib.auth.hashers import make_password

# Create your models here.

class Usuario(models.Model):
    types_ORS = [
        ("1", "AGUASCALIENTES"),
        ("2", "BAJA CALIFORNIA"),
        ("3", "BAJA CALIFORNIA SUR"),
        ("4", "CAMPECHE"),
        ("5", "COAHUILA"),
        ("6", "COLIMA"),
        ("7", "CHIAPAS"),
        ("8", "CHIHUAHUA"),
        ("9", "CDMX"),
        ("10", "DURANGO"),
        ("11", "GUANAJUATO"),
        ("12", "GUERRERO"),
        ("13", "HIDALGO"),
        ("14", "JALISCO"),
        ("15", "EDOMEX"),
        ("16", "MICHOACÁN"),
        ("17", "MORELOS"),
        ("18", "NAYARIT"),
        ("19", "NUEVO LEÓN"),
        ("20", "OAXACA"),
        ("21", "PUEBLA"),
        ("22", "QUERÉTARO"),
        ("23", "QUINTANA ROO"),
        ("24", "SAN LUIS POTOSÍ"),
        ("25", "SINALOA"),
        ("26", "SONORA"),
        ("27", "TABASCO"),
        ("28", "TAMAULIPAS"),
        ("29", "TLAXCALA"),
        ("30", "VERACRUZ"),
        ("31", "YUCATÁN"),
        ("32", "ZACATECAS"),
    ]
    types_user = [
        ("1" , "Administrador"),
        ("2", "Validador"),
        ("3", "Capturador"),
    ]
    types_disp = [
        ("1" , "Android"),
        ("2", "IPhone"),
        ("3", "Otro"),
    ]
    idUser = models.AutoField(primary_key=True)
    nickname = models.CharField(max_length = 30)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=200)
    password = models.CharField(max_length=250)
    str_pass = models.CharField(max_length=250, blank=True, default="")
    estado = models.CharField(max_length=2, choices=types_ORS, default="9")
    tipo = models.CharField(max_length=1, choices=types_user, default="3")
    tipo_disp = models.CharField(max_length=1, choices=types_disp, default="1")

    def save(self, *args, **kwargs):
        self.password = make_password(self.password)
        super(Usuario, self).save(*args, **kwargs)

    def __str__(self):
        return  " {id}, {nickname}, {state}, {type}".format(id = self.idUser, nickname = self.nickname, state = self.estado, type = self.tipo)

class Paises(models.Model):
    idPais = models.AutoField(primary_key=True)
    nombre_pais = models.CharField(max_length=250)
    iso3 = models.CharField(max_length=3, null=True)

    def __str__(self):
        return " {id}, {pais}, {iso3}".format(id = self.idPais, pais = self.nombre_pais, iso3 = self.iso3)
    
class Frases(models.Model):
    quote = models.CharField(max_length=250)
    author = models.CharField(max_length=250)

    def __str__(self):
        return " {quote}, {author}".format(
            quote = self.quote[0:30], 
            author = self.author)
    
class MsgUpdate(models.Model):
    idMsg = models.AutoField(primary_key=True)
    version = models.CharField(max_length=25)
    info = models.BooleanField(default=False)
    msg = models.CharField(max_length=500,blank=True)

    def __str__(self):
        return "{id} -> {version}v, {msg}".format(
            id = self.idMsg,
            version = self.version,
            msg = self.msg[0:25]) 
    
class Municipios(models.Model):
    idMunicipio = models.AutoField(primary_key=True)
    estado = models.CharField(max_length=250)
    estadoAbr = models.CharField(max_length=50)
    nomMunicipio = models.CharField(max_length=250)

    def __str__(self):
        return " {estadoAbr}, {nomMunicipio}".format(
            estadoAbr = self.estadoAbr, 
            nomMunicipio = self.nomMunicipio)


class PuntosInternacion(models.Model):
    idPuntoInter = models.AutoField(primary_key=True)
    nombrePunto = models.CharField(max_length=100)
    estadoPunto = models.CharField(max_length=100)
    tipoPunto = models.CharField(max_length=50)

    def __str__(self):
        return " {nombrePunto}, {estadoPunto}, {tipoPunto}".format(
            nombrePunto = self.nombrePunto, 
            estadoPunto = self.estadoPunto, 
            tipoPunto = self.tipoPunto)

class Inadmitido(models.Model):
    GENERO_CHOICES = [
        ('H', 'Hombre'),
        ('M', 'Mujer'),
        ('X', 'No especificado'),
    ]

    fecha_hora = models.DateTimeField(db_index=True)
    oficina = models.CharField(max_length=50, db_index=True)
    puntoInter = models.CharField(max_length=100)
    nac = models.CharField(max_length=100, db_index=True)
    nombreCompleto = models.CharField(max_length=250)
    nacimiento = models.DateField()
    genero = models.CharField(
        max_length=1,
        choices=GENERO_CHOICES,
        db_index=True,
        default="X"
    )
    edad = models.IntegerField( null=True, verbose_name="Edad")

    def __str__(self):
        return "{fecha}: {oficina} -->[{nac}={adulto},{genero}]".format(
            fecha = self.fecha_hora.strftime("%d/%m/%Y"),
            oficina = self.oficina,
            nac = self.nac, 
            adulto = "A" if self.edad >= 18 else "M",
            genero=self.genero)

class EstadoFuerza(models.Model):
    idEdoFuerza = models.AutoField(primary_key=True)
    oficinaR = models.CharField(max_length=50)
    numPunto = models.IntegerField()
    nomPuntoRevision = models.CharField(max_length=350)
    tipoP = models.CharField(max_length=50)
    ubicacion = models.CharField(max_length=300)
    coordenadasTexto = models.CharField(max_length=300)
    latitud = models.FloatField(default=0.0)
    longitud = models.FloatField(default=0.0)
    personalINM = models.IntegerField()
    personalSEDENA = models.IntegerField()
    personalMarina = models.IntegerField()
    personalGuardiaN = models.IntegerField()
    personalOTROS = models.IntegerField()
    vehiculos = models.IntegerField()
    seccion = models.IntegerField()

    def __str__(self):
        return "{id}, {oficina}, {nomPuntoRevision} --> {tipoP}".format(id = self.idEdoFuerza, 
                                                                      oficina = self.oficinaR, 
                                                                      nomPuntoRevision = self.nomPuntoRevision[0:25], 
                                                                      tipoP = self.tipoP)


class RescatePunto(models.Model):
    idRescate = models.AutoField(primary_key=True)
    oficinaRepre = models.CharField(max_length=50, db_index=True)
    fecha = models.CharField(max_length=10, db_index=True)
    hora = models.CharField(max_length=5)
    
    nombreAgente = models.CharField(max_length=300,blank=True)

    aeropuerto = models.BooleanField(default=False)
    carretero = models.BooleanField(default=False)
    tipoVehic = models.CharField(max_length=30, blank=True)
    lineaAutobus = models.CharField(max_length=50, blank=True)
    numeroEcono = models.CharField(max_length=50, blank=True)
    placas = models.CharField(max_length=20, blank=True)

    vehiculoAseg = models.BooleanField(default=False)
    casaSeguridad = models.BooleanField(default=False)
    centralAutobus = models.BooleanField(default=False)
    ferrocarril = models.BooleanField(default=False)
    empresa = models.CharField(max_length=150, blank=True)
    hotel = models.BooleanField(default=False)
    nombreHotel = models.CharField(max_length=100, blank=True)
    
    puestosADispo = models.BooleanField(default=False)
    juezCalif = models.BooleanField(default=False)
    reclusorio = models.BooleanField(default=False)
    policiaFede = models.BooleanField(default=False)
    dif = models.BooleanField(default=False)
    policiaEsta = models.BooleanField(default=False)
    policiaMuni = models.BooleanField(default=False)
    guardiaNaci = models.BooleanField(default=False)
    fiscalia = models.BooleanField(default=False)
    otrasAuto = models.BooleanField(default=False)

    voluntarios = models.BooleanField(default=False)
    otro = models.BooleanField(default=False)
    presuntosDelincuentes = models.BooleanField(default=False)
    numPresuntosDelincuentes = models.IntegerField()
    municipio = models.CharField(max_length=200, blank=True)
    puntoEstra = models.CharField(max_length=250, blank=True, db_index=True)
    
    nacionalidad = models.CharField(max_length=100)
    iso3 = models.CharField(max_length=3)
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=150)
    noIdentidad = models.CharField(max_length=50)
    parentesco = models.CharField(max_length=50, blank=True)
    fechaNacimiento = models.CharField(max_length=10)
    sexo = models.BooleanField(default=False)
    embarazo = models.BooleanField(default=False)
    numFamilia = models.IntegerField(blank=True)
    edad = models.IntegerField()

    def __str__(self):
        tipoE = ""
        tipo= ""
        if(self.edad > 18):
            tipoE = "A"
        else:
            tipoE = "NNA"

        if(self.aeropuerto):
            tipo = "Aeropuerto"
        elif(self.carretero):
            tipo= "Carretero"
        elif(self.casaSeguridad):
            tipo= "Casa de Seguridad"
        elif(self.centralAutobus):
            tipo= "Central de Autobús"
        elif(self.ferrocarril):
            tipo= "Ferrocarril"
        elif(self.hotel):
            tipo= "Hotel"
        elif(self.puestosADispo):
            tipo= "Puestos a Disposición"
        elif(self.voluntarios):
            tipo= "Voluntarios"
        elif(self.otro):
            tipo= "Otro"
        else:
            tipo = ""
        return "{id}.- OR: {oficinaRepre}, Fecha: {fecha} {hora}, Tipo: {tipo} --> {iso3}, {tipoE}".format(id = self.idRescate, 
                                                                      oficinaRepre = self.oficinaRepre, 
                                                                      fecha = self.fecha, 
                                                                      hora = self.hora, 
                                                                      tipo = tipo, 
                                                                      iso3 = self.iso3, 

RUIeServer/usuario/forms.py
from django import forms
from django.contrib.admin import widgets
import django.forms.widgets 
import datetime

from django import forms
from .models import EstadoFuerza

class CargarArchivoForm(forms.Form):
    archivo = forms.FileField()

class ExcelForm(forms.Form):
    year = (datetime.date.today()).strftime("%Y")
    YEARS = []
    for i in range(10):
        f = int(year) - i
        YEARS.append(str(f))

    types_ORS = [
        ("AGUASCALIENTES", "AGUASCALIENTES"),
        ("BAJA CALIFORNIA", "BAJA CALIFORNIA"),
        ("BAJA CALIFORNIA SUR", "BAJA CALIFORNIA SUR"),
        ("CAMPECHE", "CAMPECHE"),
        ("COAHUILA", "COAHUILA"),
        ("COLIMA", "COLIMA"),
        ("CHIAPAS", "CHIAPAS"),
        ("CHIHUAHUA", "CHIHUAHUA"),
        ("CDMX", "CDMX"),
        ("DURANGO", "DURANGO"),
        ("GUANAJUATO", "GUANAJUATO"),
        ("GUERRERO", "GUERRERO"),
        ("HIDALGO", "HIDALGO"),
        ("JALISCO", "JALISCO"),
        ("EDOMEX", "EDOMEX"),
        ("MICHOACÁN", "MICHOACÁN"),
        ("MORELOS", "MORELOS"),
        ("NAYARIT", "NAYARIT"),
        ("NUEVO LEÓN", "NUEVO LEÓN"),
        ("OAXACA", "OAXACA"),
        ("PUEBLA", "PUEBLA"),
        ("QUERÉTARO", "QUERÉTARO"),
        ("QUINTANA ROO", "QUINTANA ROO"),
        ("SAN LUIS POTOSÍ", "SAN LUIS POTOSÍ"),
        ("SINALOA", "SINALOA"),
        ("SONORA", "SONORA"),
        ("TABASCO", "TABASCO"),
        ("TAMAULIPAS", "TAMAULIPAS"),
        ("TLAXCALA", "TLAXCALA"),
        ("VERACRUZ", "VERACRUZ"),
        ("YUCATÁN", "YUCATÁN"),
        ("ZACATECAS", "ZACATECAS"),
    ]
    fechaDescarga = forms.DateField(
    widget=forms.SelectDateWidget(
        years=YEARS
    ))
    oficina = forms.ChoiceField(choices=types_ORS)
    # fechaDescarga2 = forms.DateField(widget=forms.SelectDateWidget)

class ExcelFormOr(forms.Form):
    year = (datetime.date.today()).strftime("%Y")
    YEARS = []
    for i in range(10):
        f = int(year) - i
        YEARS.append(str(f))

    fechaDescarga = forms.DateField(
    widget=forms.SelectDateWidget(
        years=YEARS
    ))

class ExcelFormOrs(forms.Form):
    fechaDescarga = forms.DateField()
    oficina = forms.CharField()
    # fechaDescarga2 = forms.DateField(widget=forms.SelectDateWidget)


class ExcelFormUsers(forms.Form):
    oficina = forms.CharField()

RUIeServer/dashboard/templates/dashboard/anadirPunto.html
{% extends "base/base.html" %}

{% load static %}

{% block styles %}

    <style>


        table {
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #e1e1e1
        }

        th {

            color: rgb(165, 27, 27);
        }

        .bdtable {
            border: 2px solid #b4b4b4;
            border-radius: 15px;
            box-shadow: 0px 1px;
            margin-left: 100px;
            margin-right: 100px;
  
        }
        .edit{
            border: 2px solid #f2eddf;
            background-color: #f2eddf;
            border-radius: 15px;
            box-shadow: 0px 1px;
            margin-left: 100px;
            margin-right: 100px;
            margin-top: 100px;
            opacity: 0.75;
        }
        .elegant-input-label {
            display: block;
            font-weight: bold;
            margin-bottom: 8px;
        }
    
        .elegant-input {
            width: 100%;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            margin-bottom: 15px;
            padding: 8px; 
        }
        </style>
        {% endblock styles %}

{% block content %}


{% if user.is_authenticated %}


    <!-- tablas de prueba
    <div class="bdtable bg-inm-marron-100">
        <table>
            <tr>
                <th>Oficina de Representación</th>
                <th>Nombre del Punto</th>
                <th>Tipo del Punto</th>
            </tr>
      
                <tr>
                    <td>{{ data.oficinaR }}</td>
                    <td>{{ data.nomPuntoRevision }}</td>
                    <td>{{ data.tipoP }}</td>
                </tr>
    
        </table>

    </div>-->
    
    <div class="edit">
        <br><br>
        <form method="POST" action="#" style="text-align: center; max-width: 300px; margin: auto;"> {% csrf_token %}

        
                
            
            <label for="fname" class="elegant-input-label">Oficina de Representacion:</label><br>
            <!--<input type="text" name="oficinaR" value="{{ form.oficinaR }}" class="elegant-input" id="id_oficinaR"><br>-->
            <select name="oficinaR" value="{{ form.oficinaR }}" class="elegant-input" id="id_oficinaR">
                <option value="AGUASCALIENTES">AGUASCALIENTES</option>
                <option value="BAJA CALIFORNIA">BAJA CALIFORNIA</option>
                <option value="BAJA CALIFORNIA SUR">BAJA CALIFORNIA SUR</option>
                <option value="CAMPECHE">CAMPECHE</option>
                <option value="CDMX">CDMX</option>
                <option value="CHIAPAS">CHIAPAS</option>
                <option value="CHIHUAHA">CHIHUAHUA</option>
                <option value="COAHUILA">COAHUILA</option>
                <option value="COLIMA">COLIMA</option>
                <option value="DURANGO">DURANGO</option>
                <option value="EDOMEX">EDOMEX</option>
                <option value="GUERRERO">GUERRERO</option>
                <option value="GUANAJUATO">GUANAJUATO</option>
                <option value="HIDALGO">HIDALGO</option>
                <option value="JALISCO">JALISCO</option>
                <option value="MICHOACÁN">MICHOACÁN</option>
                <option value="MORELOS">MORELOS</option>
                <option value="NAYARIT">NAYARIT</option>
                <option value="NUEVO LEÓN">NUEVO LEÓN</option>
                <option value="OAXACA">OAXACA</option>
                <option value="PUEBLA">PUEBLA</option>
                <option value="QUERÉTARO">QUERÉTARO</option>
                <option value="QUINTANA ROO">QUINTANA ROO</option>
                <option value="SAN LUIS POTOSÍ">SAN LUIS POTOSÍ</option>
                <option value="SINALOA">SINALOA</option>
                <option value="SONORA">SONORA</option>
                <option value="TABASCO">TABASCO</option>
                <option value="TAMAULIPAS">TAMAULIPAS</option>
                <option value="TLAXCALA">TLAXCALA</option>
                <option value="VERACRUZ">VERACRUZ</option>
                <option value="YUCATÁN">YUCATÁN</option>
                <option value="ZACATECAS">ZACATECAS</option>

            </select><br>
        
            <label for="lname" class="elegant-input-label">Número de Punto:</label><br>
            <input type="text" id="id_numPunto" name="numPunto" value="{{ form.numPunto }}" class="elegant-input"><br>
        
            <label for="lname" class="elegant-input-label">Nombre del Punto de Revisión:</label><br>
            <input type="text" id="id_nomPuntoRevision" name="nomPuntoRevision" value="{{ form.nomPuntoRevision }}" class="elegant-input"><br>

            <label for="lname" class="elegant-input-label">Tipo de Punto:</label><br>
            <!--<input type="text" id="id_tipoP" name="tipoP" value="{{ form.tipoP }}" class="elegant-input"><br>-->
            <select type="text" id="id_tipoP" name="tipoP" value="{{ form.tipoP }}" class="elegant-input">
                <option value="Aeropuerto" {% if form.tipoP == 'Aeropuerto' %}selected{% endif %}>Aeropuerto</option>
                <option value="Carretero" {% if form.tipoP == 'Carretero' %}selected{% endif %}>Carretero</option>
                <option value="Casa de Seguridad" {% if form.tipoP == 'Casa de Seguridad' %}selected{% endif %}>Casa de Seguridad</option>
                <option value="Central de autobús" {% if form.tipoP == 'Central de autobús' %}selected{% endif %}>Central de autobús</option>
                <option value="Ferroviario" {% if form.tipoP == 'Ferroviario' %}selected{% endif %}>Ferroviario</option>
                <option value="Hotel" {% if form.tipoP == 'Hotel' %}selected{% endif %}>Hotel</option>
                <option value="MARÍTIMOS" {% if form.tipoP == 'MARÍTIMOS' %}selected{% endif %}>MARÍTIMOS</option>
                <option value="Puestos a Disposición" {% if form.tipoP == 'Puestos a Disposición' %}selected{% endif %}>Puestos a Disposición</option>
                <option value="Volanta Móvil" {% if form.tipoP == 'Volanta Móvil' %}selected{% endif %}>Volanta Móvil</option>
                <option value="Voluntarios" {% if form.tipoP == 'Voluntarios' %}selected{% endif %}>Voluntarios</option>
                <option value="Otro" {% if form.tipoP == 'Otro' %}selected{% endif %}>Otro</option>
            </select><br>

            <label for="lname" class="elegant-input-label">Ubicación:</label><br>
            <input type="text" id="id_ubicacion" name="ubicacion" value="{{ form.ubicacion }}" class="elegant-input"><br>

            <label for="lname" class="elegant-input-label">Coordenadas Texto:</label><br>
            <input type="text" id="id_coordenadasTexto" name="coordenadasTexto" value="{{ form.coordenadasTexto }}" class="elegant-input"><br>

            <label for="lname" class="elegant-input-label">Latitud:</label><br>
            <input type="text" step=0.01 id="id_latitud" name="latitud" value="{{ form.latitud }}" class="elegant-input"><br>


            <label for="lname" class="elegant-input-label">Longitud:</label><br>
            <input type="text" step=0.01 id="id_longitud" name="longitud" value="{{ form.longitud }}" class="elegant-input"><br>
            
            <label for="lname" class="elegant-input-label">Personal INM:</label><br>
            <input type="text" id="id_personalINM" name="personalINM" value="{{ form.personalINM }}" class="elegant-input"><br>

            <label for="lname" class="elegant-input-label">Personal SEDENA:</label><br>
            <input type="text" id="id_personalSEDENA" name="personalSEDENA" value="{{ form.personalSEDENA }}" class="elegant-input"><br>

            <label for="lname" class="elegant-input-label">Personal Marina:</label><br>
            <input type="text" id="id_personalMarina" name="personalMarina" value="{{ form.personalMarina }}" class="elegant-input"><br>

            <label for="lname" class="elegant-input-label">Personal Guardia Nacional:</label><br>
            <input type="text" id="id_personalGuardiaN" name="personalGuardiaN" value="{{ form.personalGuardiaN }}" class="elegant-input"><br>

            <label for="lname" class="elegant-input-label">Personal OTROS:</label><br>
            <input type="text" id="id_personalOTROS" name="personalOTROS" value="{{ form.personalOTROS }}" class="elegant-input"><br>

            <label for="lname" class="elegant-input-label">Vehiculos:</label><br>
            <input type="text" id="id_vehiculos" name="vehiculos" value="{{ form.vehiculos }}" class="elegant-input""><br>

            <label for="lname" class="elegant-input-label">Sección:</label><br>
            <input type="text" id="id_seccion" name="seccion" value="{{ form.seccion  }}" class="elegant-input"><br>
            
            <br>
            <input type="submit" value="Añadir" style="background-color: #4CAF50; color: white; padding: 10px 15px; border: none; border-radius: 4px; cursor: pointer;">
        </form>
        <br>
        
    </div>
    
    <script>
        cambiar();
        function cambiar(){
            var lat = document.getElementById("id_latitud");
            var long = document.getElementById("id_longitud");

            var str_lat = lat.value.replace(",",".");
            var str_long = lat.value.replace(",",".");

            lat.value = str_lat;
            long.value = str_long;
        }
        
        
    </script>
</div>

{% endif %}
  
{% endblock content %}